# Generated by Django 5.2.17 on 2026-09-16 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Career_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('INTERNSHIP', 'Internship')], default='FULL_TIME', max_length=20),
        ),
    ]
