# Generated by Django 5.2.17 on 2026-09-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Career_page', '0002_alter_job_job_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='category',
        ),
        migrations.AddField(
            model_name='job',
            name='department',
            field=models.CharField(choices=[('astrology', 'Astrology'), ('customer_support', 'Customer Support'), ('sales', 'Sales'), ('marketing', 'Marketing'), ('content', 'Content & Social Media'), ('technology', 'Technology'), ('product', 'Product'), ('hr', 'Human Resources'), ('finance', 'Finance'), ('legal', 'Legal'), ('business_development', 'Business Development')], default='astrology', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='max_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='min_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
