# Generated by Django 5.2.17 on 2026-09-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Career_page', '0003_remove_job_category_job_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='w_mode',
            new_name='work_mode',
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(default='Noida Sec 59 ,Uttar Pradesh', max_length=100),
        ),
    ]
