# Generated by Django 5.2.17 on 2026-09-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Career_page', '0004_rename_w_mode_job_work_mode_alter_job_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='max_salary',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='min_salary',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
